# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: futebol_development

test:
  <<: *default
  database: futebol_test

# Para produção, o Rails usará a variável de ambiente DATABASE_URL,
# que será fornecida pela plataforma de hospedagem (Fly.io).
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
